// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChB2B-JgrSG82OobxFc_raqWxplUhk6KE',
    appId: '1:704220234860:web:9aa18b1623248fef5a4449',
    messagingSenderId: '704220234860',
    projectId: 'controldegastosperu',
    authDomain: 'controldegastosperu.firebaseapp.com',
    storageBucket: 'controldegastosperu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7uL1SMfhXn-ljL1RC_Bbwyuqm_jyjehU',
    appId: '1:704220234860:android:61d41889034661a05a4449',
    messagingSenderId: '704220234860',
    projectId: 'controldegastosperu',
    storageBucket: 'controldegastosperu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqdgz4_upZ0MdToYT7fXf8AJmHYoX1JE',
    appId: '1:704220234860:ios:e0ba0a5dabb339b45a4449',
    messagingSenderId: '704220234860',
    projectId: 'controldegastosperu',
    storageBucket: 'controldegastosperu.appspot.com',
    iosClientId: '704220234860-v07a7oa2di1137dikmhma0p816tqe4k3.apps.googleusercontent.com',
    iosBundleId: 'com.controlgastos.controldegastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzqdgz4_upZ0MdToYT7fXf8AJmHYoX1JE',
    appId: '1:704220234860:ios:25d1e4a3f56f849b5a4449',
    messagingSenderId: '704220234860',
    projectId: 'controldegastosperu',
    storageBucket: 'controldegastosperu.appspot.com',
    iosClientId: '704220234860-t0p77aloica9ev4jhndjlffq3atap03f.apps.googleusercontent.com',
    iosBundleId: 'com.controlgastos.controldegastos.RunnerTests',
  );
}
