// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OPQk1w8JmRKkjJiV-ol6_RYewF39ZjA',
    appId: '1:546463673476:web:c56c1394aba6c8b4bd66d1',
    messagingSenderId: '546463673476',
    projectId: 'appbibliotecaa',
    authDomain: 'appbibliotecaa.firebaseapp.com',
    storageBucket: 'appbibliotecaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfioe1lCP-32A1xBbJrUHFFDnQnXuYls',
    appId: '1:546463673476:android:6a76a70de44c323ebd66d1',
    messagingSenderId: '546463673476',
    projectId: 'appbibliotecaa',
    storageBucket: 'appbibliotecaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdnzo_2qzXNxg4mB_qujoHQNTDXZaY2xM',
    appId: '1:546463673476:ios:ab1a87de390e4105bd66d1',
    messagingSenderId: '546463673476',
    projectId: 'appbibliotecaa',
    storageBucket: 'appbibliotecaa.appspot.com',
    iosClientId: '546463673476-ll4gr6oqj942ld0v8jprpu0lo4npf9b6.apps.googleusercontent.com',
    iosBundleId: 'com.controlgastos.bibliotecaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdnzo_2qzXNxg4mB_qujoHQNTDXZaY2xM',
    appId: '1:546463673476:ios:94b4a4d8e7ee3f43bd66d1',
    messagingSenderId: '546463673476',
    projectId: 'appbibliotecaa',
    storageBucket: 'appbibliotecaa.appspot.com',
    iosClientId: '546463673476-6rn6gosg9a1euiuul8t13lea0gpe7gvr.apps.googleusercontent.com',
    iosBundleId: 'com.controlgastos.bibliotecaApp.RunnerTests',
  );
}
